front login and register pages
Koci0/code-matcher pull request #2
Opened 2021-04-28 13:29 UTC by uniQueSense

2021-04-29 12:23 UTC, ParleJe requested changes
Reposition media queries to the end of css, it's way more pleasant to view

2021-04-29 12:23 UTC, ParleJe commented on src/App.js
> +    <Route path="/" exact component={Login}/>
I think its redundant pathing. Path "/" will match "/login". Remove this like and try, if it works change it

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
These classes can be ID's

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    background: #F6F6F6;
introduce css variable for colours. [link](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    border: 0;;
double semicolon

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
You don't change font-size, so why are you typing it again in another media query?

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +        font-size: 1.5em;
as above, why again?

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    border-color: #F6F6F6;
css variable

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    color: #F6F6F6;
css variable

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
is it possible to reduce number of breakpoints?

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    color: #F06449;
css variable

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +    color: white;
css variable

2021-04-29 12:23 UTC, ParleJe commented on src/Register.css
> +    background: #1B1D2B;
css variable

2021-04-29 12:23 UTC, ParleJe commented on src/Register.css
> +}
They override themselves

2021-04-29 12:23 UTC, ParleJe commented on src/Register.css
> +    background: #292B2D;
variable

2021-04-29 12:23 UTC, ParleJe commented on src/Register.css
> +}
you have media query for 1600px above, use it

2021-04-29 12:23 UTC, ParleJe commented on src/Register.css
> +    color: #F6F6F6;
css variables

2021-04-29 12:23 UTC, ParleJe commented on src/Register.js
> +import {  FaLinkedin, FaGithub, FaFacebook } from "react-icons/fa";
double spacebar on after curly bracket

2021-04-29 12:23 UTC, ParleJe commented on src/Register.js
> +export default Register;
no new line on end of file

2021-04-29 12:23 UTC, ParleJe commented on src/Login.js
> +export default Login;
lack of new line at the end

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
you already have media query for 910px, merge them

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
media query already exists for 910px

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
empty query

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
same query above

2021-04-29 12:23 UTC, ParleJe commented on src/Login.css
> +}
isn't it include in index css under "*"?

2021-05-04 12:02 UTC, ParleJe requested changes
Formik to delete!!! It's not used dependency

2021-05-04 15:56 UTC, uniQueSense commented on package.json
> +    "formik": "^2.2.6",
Thank you for your attention. I hope this commit is the last one and you merge my branch.

2021-05-04 17:21 UTC, ParleJe approved these changes
OK

2021-05-04 17:21 UTC, merged