added security and login, register endpoints
Koci0/code-matcher pull request #4
Opened 2021-05-04 15:08 UTC by Bartosz007

2021-05-05 07:18 UTC, ParleJe requested changes

2021-05-05 07:18 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/controllers/SecurityController.java
> +        }
You can catch AuthenticationException, one catch block less

2021-05-05 07:18 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/mappers/UserMapper.java
> +    })
if field in source and target has the same name, napping annotation is redundant

2021-05-05 07:18 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/repositories/UserRepository.java
> +    Optional<User> findByEmail(String email) throws UsernameNotFoundException;
Doesn't optional is enough? If username wouldnt be found, optional will have null, and we can check for it. Or this exception is inherited?

2021-05-05 07:18 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/services/SecurityService.java
> +    }
if this throws, findByEmail could not throw. I'm not sure about it, I'm open for discussion

2021-05-05 18:36 UTC, Bartosz007 commented on src/main/java/pl/codematcher/codematcherbackend/controllers/SecurityController.java
> +        }
A w jakim celu? To łapie dwa różne wyjątki

2021-05-05 18:46 UTC, Bartosz007 commented on src/main/java/pl/codematcher/codematcherbackend/mappers/UserMapper.java
> +    })
Wzorowałem się na Twoim kodzie, ale poprawione.

2021-05-05 18:51 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/controllers/SecurityController.java
> +        }
Ale nic konkretnego z nimi potem nie robisz żeby takie rozróżnienie było potrzebne, ale ok rozumiem

2021-05-05 18:51 UTC, Bartosz007 commented on src/main/java/pl/codematcher/codematcherbackend/services/SecurityService.java
> +    }
Nie za bardzo rozumiem o co chodzi. Tam muszę dać .orElseThrow, bo kompilator nie puści

2021-05-05 18:55 UTC, ParleJe commented on src/main/java/pl/codematcher/codematcherbackend/mappers/UserMapper.java
> +    })
Dopiero potem się okazało to niepotrzebne xD

2021-05-06 08:33 UTC, Bartosz007 commented on src/main/java/pl/codematcher/codematcherbackend/controllers/SecurityController.java
> +        }
Łatwiej jest z błędu wyczytać co jest nie tak

2021-05-06 08:44 UTC, ParleJe approved these changes
To merge

2021-05-06 08:55 UTC, merged