Tidy up from merging, simple api calls
Koci0/code-matcher pull request #7
Opened 2021-05-11 18:50 UTC by ParleJe

I came up with some kind of structure and tidied up files from different merges. Moreover there are simple API calls for logging in and registering. When using make sure that URL is valid for you. Open to criticism of course :)

2021-05-11 19:22 UTC, uniQueSense requested changes

2021-05-13 11:53 UTC, merged

2021-05-13 16:19 UTC, ParleJe commented on src/APICalls/index.js
> +import {Log, Register} from './usersApi';
well, importujesz jeden obiekt ze wszystkimi funkcjami zamiast każdej z osobna z różnych plików, łatwiej się odnaleźć.

2021-05-13 16:20 UTC, ParleJe commented on src/mainViews/Login.js
> +        return <Redirect to='/MyProjects' />
To na razie tak na sztywno zapisałem, ogólnie jak logowanie się powiedzie isLog jest true i nie chcemy renderować strony logowania tylko już inną stronę, po to redirect

2021-05-13 16:22 UTC, ParleJe commented on src/mainViews/Login.js
> +    const [password, setPassword] = useState('');
Zostawiłem '' żeby ten kto czyta kod widział od razu że tam będą stringi w tym state'cie, ale tak można by
 się ich pozbyć